<script>
import LogoSvg from "../components/Logo.vue";

export default {
  components: { LogoSvg },
};
</script>

<template>
  <div class="container">
    <h1>Summary of development</h1>
    <img src="/assets/summary.png" alt="cat_with_pc" width="300" />
    <div class="toc">
      <ol>
        <li><a href="#sum-1" class="anchor">Final outputs</a></li>
        <li><a href="#sum-2" class="anchor">Analyse requirement</a></li>
        <li><a href="#sum-3" class="anchor">Create wireframe</a></li>
        <li>
          <a href="#sum-4" class="anchor"
            >Choose a technologies and frameworks
          </a>
        </li>
        <li><a href="#sum-5" class="anchor">Prepare independent library</a></li>
        <li><a href="#sum-6" class="anchor">Figure out Socket.io</a></li>
        <li><a href="#sum-7" class="anchor">Figure out r/w JSON file</a></li>
        <li><a href="#sum-8" class="anchor">Implement elements to Vue</a></li>
        <li><a href="#sum-9" class="anchor">Implement designs to CSS</a></li>
        <li><a href="#sum-10" class="anchor">Check it works in Codio</a></li>
        <li><a href="#sum-11" class="anchor">Refactoring</a></li>
        <li><a href="#sum-12" class="anchor">Responsive</a></li>
        <li><a href="#sum-13" class="anchor">Further improvements</a></li>
      </ol>
    </div>
    <div class="summary">
      <section id="sum-1">
        <h3>1. Final outputs</h3>
        <ul>
          <!--          FIX ME-->
          <li>Github repository: <a href="">chat-app/azusaw</a></li>
          <li>Codio path: /CA4/....</li>
        </ul>
        <p></p>
        <h4>Architecture</h4>
        <p>
          基本的にはテンプレートとして配布されたファイルと同じ構成である。Wikiページの更新のためのファイルr/wは、ExpressでのHTTP
          request経由で行うように実装した。
        </p>
        <img src="/assets/summary/arch.jpg" alt="architecture" />
        <h4>How to deploy</h4>
        <ol>
          <li>
            Execute <code>npm run build</code> in /front to generate html and js
            file
          </li>
          <li>
            The files generated by build command are placed in /server/public
            automatically
          </li>
          <li>
            Execute <code>node index.js</code> in /server to start the server
          </li>
        </ol>
      </section>

      <section id="sum-2">
        <h3>2. Analyse requirement</h3>
        <p>First, I checked the requirement from documents and organized.</p>
        <ul>
          <li>Home page: general information</li>
          <li>About page: further details</li>
          <li>Wiki page: professional Wiki on a topic, hobby or interest</li>
          <li>Summary page: summarise my development process</li>
          <li>Chat page: real time chat function</li>
        </ul>
        <h4>About chat function...</h4>
        <ul>
          <li>Notification to existing users when a new users’ joins</li>
          <li>Show a list of users currently within a chat</li>
          <li>
            Inform below event to users
            <ul>
              <li>When a new user joins a chat users</li>
              <li>when a user exits a chat</li>
              <li>when other connected users are typing</li>
            </ul>
          </li>
        </ul>
      </section>

      <section id="sum-3">
        <h3>3. Create wireframe</h3>
        <p>
          Consider a simple screen structure. Detailed designs are not drawn up
          in wireframes, but considered as they are implemented.
        </p>
        <p>
          A one-column design was used for the layout throughout the weitebs.
          This is because it is relatively easy to make responsive and make it
          looks simple. Footers and headers are placed on all pages as common
          components.
        </p>
        <img src="/assets/summary/wf.jpg" alt="main wireframe" width="500" />
        <h4>Chat page</h4>
        <p>
          The design of the chat page is based on Slack, Microsoft Teams and
          other chat applications as a reference because most chat apps design
          are generally similar and are considered to be sophisticated.
        </p>
        <img
          src="/assets/summary/wf-chat.jpg"
          alt="chat wireframe"
          width="500"
        />
        <h4>Wiki page</h4>
        <p>
          In wiki page, detailed information is able to be opened and closed,
          and the expanded area should be editable. It should be controlled in
          place so that multiple items can not be edited at the same time.
        </p>
        <img
          src="/assets/summary/wf-wiki.jpg"
          alt="wiki wireframe"
          width="500"
        />
      </section>

      <section id="sum-4">
        <h3>4. Choose a technologies and frameworks</h3>
        <p>The framework I have chosen and reasons.</p>
        <blockquote>
          <strong>Vue.js</strong> is an open-source model–view–viewmodel front
          end JavaScript framework for building user interfaces and single-page
          applications. It was created by Evan You, and is maintained by him and
          the rest of the active core team members.
        </blockquote>
        <h4>Server side (back-end)</h4>
        <ul>
          <li>
            <b>Express</b> ... Web application frameworks available in Node.js
          </li>
          <li>
            <b>Socket.io</b> ... Providing real-time communication between
            server and client
          </li>
        </ul>
        <h4>Client side (front-end)</h4>
        <ul>
          <li>
            <b>Vue.js</b><code>v3.2.45</code> ... JavaScript Framework
            <ul>
              <li>I have no experience</li>
              <li>Easy to introduction</li>
              <li>popular in Japan</li>
            </ul>
          </li>
          <li>
            <b>Element+</b> ... UI framework for Vue.js
            <ul>
              <li>Well written English document</li>
              <li>Easy to introduction</li>
              <li>Using material design</li>
              <li>
                18.4K stars in
                <a
                  href="https://github.com/element-plus/element-plus"
                  target="__blank"
                  >Github</a
                >
              </li>
            </ul>
          </li>
        </ul>
      </section>

      <section id="sum-5">
        <h3>5. Prepare independent library</h3>
        <h4>Vue.js</h4>
        <p>
          followed official
          <a href="https://vuejs.org/guide/quick-start.html" target="_blank"
            >Quick start guide</a
          >. Executed <code>npm init vue@latest</code> to prepare a development
          environment.
        </p>
        <p>
          The latest version of Vue.js uses <b>Vite</b> for building. Vite is a
          build tool that provides a faster and leaner development experience
          for modern web projects. The build-related scripts in package.json
          were set up as follows:
        </p>
        <pre><code>
        /* package.json */

        "scripts": {
          "dev": "vite",
          "build": "vite build",
          "preview": "vite preview --port=3000",
          "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs --fix --ignore-path .gitignore"
        },
        </code></pre>
        <ul>
          <li>
            <code>npm run build</code>
            ... command for build .vue files and generate html, css and
            Javascript files
          </li>
          <li>
            <code>npm run dev</code><code>npm run preview</code>
            ... commands for development
          </li>
        </ul>
        <h4>Element+</h4>
        <p>
          followed official
          <a
            href="https://element-plus.org/en-US/guide/quickstart.html"
            target="_blank"
            >Quick start guide</a
          >
          . Executed <code>npm install element-plus</code> and edited main.js
          file as below.
        </p>
        <pre><code>
        /* main.js */

        import { createApp } from "vue";
        import App from "./App.vue";
        import router from "./router";
        <b>import ElementPlus from "element-plus";</b>
        <b>import * as ElementPlusIconsVue from "@element-plus/icons-vue";</b>
        <b>import "element-plus/dist/index.css";</b>
        import "./styles/main.css";

        const app = createApp(App);
            app.use(router);
            <b>app.use(ElementPlus);
            for (const [key, component] of Object.entries(ElementPlusIconsVue)) {
            app.component(key, component);
        }</b>

        app.mount("#app");
        </code></pre>
      </section>

      <section id="sum-6">
        <h3>6. Figure out Socket.io</h3>
        <p>
          Referring to the samples distributed, the processes of Socket.io
          performed by the client and server respectively were checked. <br />
          Socket.io has two main functions: sending<code>emit</code> and
          receiving<code>on</code>. Clients use <code>emit</code> to notify that
          an event was happen to server, then severs received an event from
          client, then broadcast it to every clients by using
          <code>emit</code> as a callback of <code>on</code>.
        </p>
        <h4>Server side (back-end)</h4>
        <ul>
          <li>
            io.on: <code>connection</code>
            <ul>
              <li>Reserved action by socket.io</li>
              <li>When a client generate socket.io, receive an event</li>
            </ul>
          </li>
          <li>
            socket.on: <code>user connected</code>
            <ul>
              <li>
                Created for receiving an event from clients when new client
                connected
              </li>
              <li>Callback: io.emit("new user connected")</li>
            </ul>
          </li>
          <li>
            socket.on: <code>chat message</code>
            <ul>
              <li>
                Created for receiving an event from clients when new message was
                sent
              </li>
              <li>Callback: io.emit("chat message")</li>
            </ul>
          </li>
          <li>
            socket.on: "start typing"
            <ul>
              <li>
                Created for receiving an event from clients when user started
                typing
              </li>
              <li>Callback: io.emit("typing")</li>
            </ul>
          </li>
          <li>
            socket.on: <code>stop typing</code>
            <ul>
              <li>
                Created for receiving an event from clients when user stopped
                typing
              </li>
              <li>Callback: io.emit("typing")</li>
            </ul>
          </li>
          <li>
            io.on: <code>disconnect</code>
            <ul>
              <li>Reserved action by socket.io</li>
              <li>
                When a client leave or reload page socket.io, receive an event
              </li>
              <li>Callback: io.emit("user disconnected"), io.emit("typing")</li>
            </ul>
          </li>
          <li>
            io.on: <code>user disconnect</code>
            <ul>
              <li>
                Created for receiving an event from clients when user unmounted
                a page
              </li>
              <li>When a client destroy socket.io, receive an event</li>
              <li>Callback: io.emit("user disconnected"), io.emit("typing")</li>
            </ul>
          </li>
        </ul>
        <h4>Client side (front-end)</h4>
        <ul>
          <li>
            socket.emit: <code>chat messages</code>
            <ul>
              <li>
                Created for sending an event to clients when new message was
                sent
              </li>
            </ul>
          </li>
          <li>
            socket.emit: <code>start typing</code>
            <ul>
              <li>
                Created for sending an event from clients when user started
                typing
              </li>
            </ul>
          </li>
          <li>
            socket.emit: <code>stop typing</code>
            <ul>
              <li>
                Created for sending an event from clients when user stopped
                typing
              </li>
            </ul>
          </li>
          <li>
            socket.on <code>new user connected</code>
            <ul>
              <li>
                Created for receiving an event from clients when new client
                connected
              </li>
              <li>When a client destroy socket.io, receive an event</li>
              <li>Callback: io.emit("user disconnected"), io.emit("typing")</li>
            </ul>
          </li>
          <li>
            socket.on: <code>user connected</code>
            <ul>
              <li>
                Created for receiving an event from clients when new client
                connected
              </li>
              <li>Callback: update active users</li>
            </ul>
          </li>
          <li>
            socket.on: <code>chat message</code>
            <ul>
              <li>
                Created for receiving an event from clients when new message was
                sent
              </li>
              <li>Callback: update messages</li>
            </ul>
          </li>
          <li>
            socket.on: <code>typing</code>
            <ul>
              <li>
                Created for receiving an event from clients when new message was
                sent
              </li>
              <li>Callback: update typing users</li>
            </ul>
          </li>
          <li>
            socket.on: <code>user disconnect</code>
            <ul>
              <li>
                Created for receiving an event from clients when user unmounted
                a page
              </li>
              <li>When a client destroy socket.io, receive an event</li>
              <li>Callback: update active users</li>
            </ul>
          </li>
        </ul>
        <p>
          I tested and figured out how socket.io works between client and server
          with a brief UI.
        </p>
        <img src="/assets/summary/socket-test.jpg" alt="socket test page" />
      </section>

      <section id="sum-7">
        <h3>7. Figure out r/w JSON file</h3>
        <p>
          For the development of the editable wiki, I decided to use Express
          with
          <code>GET</code>and<code>PUT</code> requests from the client to the
          server implemented by Express. About the data storage method,
          read/write a data from/to the <code>JSON</code> file which is located
          server local was adopted as this is less expensive to develop than
          using a database. Using database is not mandatory requirement for this
          assessment.
        </p>
        <h4>Server side (back-end)</h4>
        <pre><code>
        /* index.js */
        const dataFile = "data.json";

        app.get("/info", (req, res) => {
          const data = JSON.parse(fs.readFileSync(dataFile, "utf8"));
          res.send(data);
        });

        app.put("/info", (req, res) => {
          let data = JSON.stringify({ contents: req.body.contents });
          fs.writeFileSync(dataFile, data);
          res.send(200);
        });
        </code></pre>
        <ul>
          <li>
            GET<code>/info</code>... read data from data.json, convert string to
            JSON object and send it
          </li>
          <li>
            PUT<code>/info</code>... convert JSON object to string and write it
            to data.json
          </li>
        </ul>
        <h4>Client side (front-end)</h4>
        <pre><code>
        methods: {
          getInfo: function () {
            fetch("/info", {
              method: "GET",
              headers: {
                Accept: "application/json",
                "Content-Type": "application/json",
              },
            })
              .then((response) => response.json())
              .then((data) => (this.contents = data.contents))
          },
          saveInfo: function (data) {
            fetch("/info", {
              method: "PUT",
              headers: {
                Accept: "application/json",
                "Content-Type": "application/json",
              },
              body: JSON.stringify(data),
            })
              .then(() => {
                this.getInfo();
              })
          },
        </code></pre>
        <ul>
          <li>
            <code>getInfo</code>... send GET request to server and assign data
            to a variable
          </li>
          <li>
            <code>saveInfo</code>... send PUT request with edited data, then
            send GET request to update data
          </li>
        </ul>
      </section>

      <section id="sum-8">
        <h3>8. Implement elements to Vue</h3>
        <p>
          Now that the functionality has been implemented, the necessary pages
          and components are prepared.<br /><br />The directory structure on the
          client side(Vue.js) is as follows, with the content of each page
          divided into files in component units.
        </p>
        <pre><code>
        > front
            > node_modules
            > public
                > assets  /*image files*/
            > src
                > components /*.vue files of component*/
                > router   /*configuration file of router*/
                > styles   /*css files*/
                > views    /*.vue files of each page*/
                App.vue    /*the root of this webapp*/
                main.js    /*initialise this root component*/
            index.html    /*entry point of Vue.js*/
            package.json
            vite.config.js   /*configuration file of vite*/
        </code></pre>
        <p>
          <br />
          The configuration of routing is below. <code>/router/index.js</code>is
          imported in main.js.
        </p>
        <pre><code>
        /* router/index.js */

        import { createRouter, createWebHistory } from "vue-router";
        import HomeView from "../views/HomeView.vue";
        import AboutView from "../views/AboutView.vue";

        const router = createRouter({
          history: createWebHistory(import.meta.env.BASE_URL),
          routes: [
            {
              path: "/",
              name: "home",
              component: HomeView,
            },
            {
              path: "/about/",
              name: "about",
              component: AboutView,
            },
                ....
          ],
        });

        export default router;
        </code></pre>
        <pre><code>
        /* App.vue */

        &lt;template>
          &lt;RouterLink class="nav-item" to="/">Home&lt;/RouterLink>
          &lt;RouterLink class="nav-item" to="/about">About&lt;/RouterLink>
          &lt;RouterLink class="nav-item" to="/chat">Chat&lt;/RouterLink>
          <b>&lt;RouterView /></b>
        &lt;templates>
        </code></pre>
        <p>
          Depending on the URL path, the configured component in
          <code>/router/index.js</code> will appear in the
          <code>&lt;RouterView /></code> location.<br />
          For example, in the case of <code>/about</code> access, a screen with
          an embedded <code>&lt;AboutView></code> in App.vue will be displayed.
        </p>
        <p>
          Regarding the syntax of the .vue file, the main feature is that each
          .vue file is constructed by three part, Javascript, HTML, and CSS.
          This is the example of <code>AboutView.vue</code>.
        </p>
        <pre><code>
        /* view/AboutView.vue */
        &lt;script>&lt;/script>

        &lt;template>
          &lt;div class="container">
            &lt;h1>About this website&lt;/h1>
            &lt;img src="/assets/about.png" alt="cat_in_box" width="300" />
            &lt;div class="text-container">
              &lt;p>
              Hello again, it's azusaw.&lt;br />
              I'm studying web development at University of Aberdeen.&lt;br />
              &lt;br />
              I created this website to learn new things of web development by
              myself&lt;br />
              and hope to help people who learn programming.&lt;br />
              &lt;/p>
              &lt;p>I hope you enjoy my website! 😊&lt;/p>
            &lt;/div>
          &lt;/div>
        &lt;/template>

        &lt;style scoped>
        .container {
          text-align: center;
        }
        .text-container {
          max-width: 500px;
          text-align: center;
          margin: 0 auto 30px;
          line-height: 1.8;
        }
        &lt;/style>
        </code></pre>
        <p>
          Javascript is written in <code>&lt;script></code> part (there are no
          Javascript in this example), HTML is in
          <code>&lt;template></code> part and CSS is
          <code>&lt;style></code> part.
        </p>
        <p>
          The advantage is that it is easier to manage components, as all the
          methods, part configurations and styles required to display a
          component can be found in a single file.
        </p>
      </section>

      <section id="sum-9">
        <h3>9. Implement designs to CSS</h3>
        <p>
          As mentioned previously, CSS properties are describes in .vue files.
          Values that I want to use in common across components, such as theme
          colours, are described as variables in
          <code>/styles/main.css</code> and can be used within each .vue file.
          <code>/styles/main.css</code> is imported in main.js.
        </p>
        <pre><code>
        /* styles/main.css */

        :root {
          <b>--primary-color: #08498a;</b>
          --secondary-color: #ea9f06;
          --header-height: 90px;
        }
        </code></pre>
        <pre><code>
        /* App.vue */

        .nav-item:hover {
          cursor: pointer;
          <b>color: var(--primary-color);</b>
          background-color: aliceblue;
          box-shadow: 0 0 20px 0 aliceblue;
          transition: 0.5s;
        }
        </code></pre>
      </section>

      <section id="sum-10">
        <h3>10. Check it works in Codio</h3>
        <p>
          Before proceeding with the development towards completion, I checked
          that it worked on Codio environment by copying all directories except
          node_modules, deploying it to Codio, executing
          <code>npm install</code> and then <code>npm build</code>.
        </p>
        <p>
          Here a problem arose: the versions of Node.js and npm in Codio and the
          local development environment were different and node version of Codio
          <code>v15.3.0</code> did not support Vue.js <code>v3</code>.
          Therefore, Node.js and npm in Codio were downgraded to match the local
          version, <code>v14.18.1</code> and <code>v6.14.15</code> For the
          version change, a Node.js version control library called n had to be
          installed.
        </p>
        <pre><code>
        > sudo npm install n -g
        > n 14.18.1
        </code></pre>
        <p>
          This confirmed that the build was successful and that the server
          worked correctly in Codio.
        </p>
      </section>

      <section id="sum-11">
        <h3>11. Refactoring</h3>
        <p>
          After the pages and functions were implemented, refactoring was done
          to make the code better. Examples of refactoring are below.
        </p>
        <ul>
          <li>
            Remove redundancies and rewrite using repetitive statements such as
            for
          </li>
          <li>
            Split components to improve readability and make them reusable in
            different components
          </li>
        </ul>
        <pre><code>
        /* App.vue */

        export default {
          components: { LogoSvg },
          data() {
          return {
            pages: [
              { name: "Home", path: "/" },
              { name: "About", path: "/about/" },
              { name: "Wiki", path: "/wiki/" },
              { name: "Summary", path: "/summary/" },
              { name: "Chat", path: "/chat/" },
            ],
          };

        &lt;template>
          :
          &lt;el-header class="header">
            &lt;LogoSvg />
            &lt;nav class="nav">
              &lt;RouterLink
                  class="nav-item"
                  <b>v-for="item in pages"</b>
                  :key="item.name"
                  :to="item.path"
              >
                { item.name }
            &lt;/RouterLink>
          &lt;/nav>
          :
        </code></pre>
      </section>

      <section id="sum-12">
        <h3>12. Responsive</h3>
        <p>
          Some UI frameworks have components that make it easy to implement
          responsive design. (e.g. Vuetify, MaterialUI) Unfortunately, Element+
          did not provide a component for responsive, so it was implemented
          using CSS media queries.
        </p>
        <pre><code>
        /* App.vue */

        &lt;style scoped>
        /* apply when screen width is smaller than 660px */
        @media screen and (max-width: 660px) {
          .pc-nav {
            display: none;
          }
        }

        /* apply when screen width is wider than 661px */
        @media screen and (min-width: 661px) {
          .mobile-nav {
            display: none;
          }
        }
        &lt;/style>
        </code></pre>
        <p>
          As described above, the CSS to be switched by screen size was
          implemented for each part to be switched. For instance, the header
          menu, buttons in home and text boxes in chat page.
        </p>
        <img src="/assets/summary/responsive.jpg" alt="responsive home" />
      </section>

      <h3 id="sum-13">13. Further improvements</h3>
      <p>Further improvements were made to improve usability and appearance.</p>
      <h4>i. Creation of random colours for each user</h4>
      <p>
        To allow users to be easily identified, a colour code was created from
        the user name random 6 digits and assigned to the background colour of
        the user icon.
      </p>
      <img src="/assets/summary/chat-color.jpg" alt="chat page" />
      <pre><code>
      /* components/MessageCard.vue */
      &lt;script>
        :
        <b>mounted() {
          /* Create a hexadecimal color cord from user name easy for each user */
          this.colorCord =
              "#" +
              Number(this.userName.slice(5) * 10)
                  .toString(16)
                  .padStart(6, "F");
        },</b>
      };
      &lt;/script>
        :
      &lt;style>
        .avatar {
          display: flex;
          float: left;
          <b>background-color: v-bind(colorCord);</b>
        }
      &lt;/style>
      </code></pre>

      <h4>ii. SVG animation</h4>
      <p>
        I used a service
        <a href="https://svgartista.net/" target="_blank">SVG ARTISTA</a>, which
        generate SVG animation from SVG as the logo of my website. The animation
        for colour loss on hover was added by myself.
      </p>
      <div class="svg-box">
        <LogoSvg />
      </div>
      <h4>iii. Submit by Ctrl + Enter</h4>
      <p>
        As implemented in many chat application tools, shortcut keys can also be
        used to submit a message. This is a Vue.js v3 feature:
        <a
          href="https://vuejs.org/guide/essentials/event-handling.html#key-modifiers"
          target="_blank"
          >Key Modifiers</a
        >
      </p>
      <pre><code>
      /* components/ChatTextBox.vue */
        :
      &lt;template>
        &lt;el-input
            class="chat-text-box"
            v-model="message"
            placeholder="Input messages here!"
            type="textarea"
            resize="none"
            :rows="4"
            :autosize="{ minRows: 4, maxRows: 4 }"
           <b>@keyup.ctrl.enter="submit"</b>
      />
      </code></pre>

      <p></p>
    </div>
  </div>
</template>

<style scoped>
.container {
  text-align: center;
}

.toc {
  text-align: left;
  padding: 5px 10px;
  color: #646b69;
  background-color: #eee;
  font-weight: 600;
  border-radius: 5px;
  margin: 0 0 40px;
  line-height: 2;
}

.summary {
  text-align: left;
}

.svg-box {
  text-align: center;
  padding: 2rem 0;
  max-width: 100%;
  background-color: #333;
}

img {
  display: block;
  margin: 1.5rem auto;
  max-width: 600px;
}

@media screen and (max-width: 650px) {
  img {
    max-width: 95vw;
  }
}

h3 {
  /* Adjust anchor position*/
  padding-top: 120px;
  margin-top: calc(var(--header-height) * -1);
  font-weight: bolder;
}

h4 {
  margin: 30px 0 5px;
  text-decoration: underline;
  font-weight: bolder;
}

blockquote {
  padding: 20px 20px 40px;
  margin: 2rem 0;
  color: #eee;
  background-color: #646b69;
  line-height: 1.5rem;
  border-radius: 5px;
}

blockquote:after {
  margin-top: 5px;
  float: right;
  content: "quoted from Wikipedia";
  text-decoration: underline;
}

code {
  color: #555;
  font-family: "Quicksand", "Noto Sans JP", "sans-serif";
  line-height: 1.5rem;
  margin: 0;
  padding: 0;
}

pre {
  background-color: #eee;
  border-radius: 5px;
  font-size: 0.9rem;
}

p {
  line-height: 1.8rem;
}

a {
  text-decoration: underline;
}

a:hover {
  cursor: pointer;
  text-decoration: underline;
}

li {
  line-height: 1.6;
  margin-bottom: 10px;
}

p > code,
ul > li > code,
ol > li > code {
  font-size: 0.8rem;
  padding: 0.2rem 0.3rem;
  margin: 0 0.3rem;
  color: #ff3c7b;
  border: #ccc 1px solid;
  border-radius: 3px;
  background-color: #eee;
  overflow-x: auto;
}

pre {
  margin-bottom: 1.5rem;
}
</style>
